services:
  db:
    image: mariadb:11
    container_name: pulsefocus-db
    environment:
      - MYSQL_ROOT_PASSWORD=pulsefocus_root
      - MYSQL_DATABASE=pulsefocus_db
      - MYSQL_USER=pulsefocus_user
      - MYSQL_PASSWORD=pulsefocus_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "3307:3306"
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pulsefocus-app
    environment:
      - APP_COMPANY_NAME=ChronaPulse Labs
      - APP_DOMAIN=focus.chronapulse.com.br
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=pulsefocus_db
      - DB_USER=pulsefocus_user
      - DB_PASSWORD=pulsefocus_pass
      - DB_CHARSET=utf8mb4
    volumes:
      - ./:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
